services:

  flask:
    build: . # Uses the Dockerfile to build the image
    container_name: flask_app
    expose:
      - "5000" # Exposes the Flask app internally
    networks:
      - app_network
    environment:
      - FLASK_ENV=production
    volumes:
      - static_content:/app/static # Shared volume for static files

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80" # Listens on port 80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - static_content:/usr/share/nginx/html/static # Serves static files from a mounted volume
    depends_on:
      - flask
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_content: