services:
  static_init:
    build: ./app
    command: cp -r /app/static/* /static_data/
    volumes:
      - static_data:/static_data
    depends_on:
      - flask

  flask:
    build: ./app # Uses the Dockerfile to build the image
    container_name: flask_app
    expose:
      - "5000" # Exposes the Flask app internally
    networks:
      - app_network
    environment:
      - FLASK_ENV=production
    volumes:
      - static_data:/app/static

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80" # EC2 listens on 8080, nginx container listens on 80
    volumes:
      - ./app/config/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/usr/share/nginx/html/static # Mount the static folder
    depends_on:
      - flask
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_data: