---
- name: Install Docker on Ubuntu
  hosts: servers
  become: true
  tasks:
    - name: Update APT package
      ansible.builtin.apt:
        update_cache: true

    - name: Install other packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add add-apt-repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package again
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started and enabled
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    # - name: Copy docker-compose.yml to the instance
    #   ansible.builtin.copy:
    #     src: ../docker-compose.yml
    #     dest: /home/ubuntu/docker-compose.yml
    #     owner: ubuntu
    #     group: ubuntu
    #     mode: "0644"

    # - name: Run docker-compose down and up
    #   ansible.builtin.shell: |
    #     docker-compose -f /home/ubuntu/docker-compose.yml down
    #     docker-compose -f /home/ubuntu/docker-compose.yml up -d
    #   args:
    #     chdir: /home/ubuntu
