---
- name: Install Docker on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update APT package
      ansible.builtin.apt:
        update_cache: true

    - name: Install other packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add add-apt-repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package again
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started and enabled
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Copy docker-compose.yml to the instance
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: docker
        mode: "0644"

    - name: Copy app directory to the instance
      ansible.builtin.copy:
        src: ../app
        dest: /home/ubuntu/
        owner: ubuntu
        group: docker
        mode: "0755"

    - name: Bring down existing containers
      ansible.builtin.command:
        cmd: docker compose -f /home/ubuntu/docker-compose.yml down
      args:
        chdir: /home/ubuntu
      register: down_result
      changed_when: down_result.rc != 0

    - name: Pull latest images
      ansible.builtin.command:
        cmd: docker compose -f /home/ubuntu/docker-compose.yml pull
      args:
        chdir: /home/ubuntu
      register: pull_result
      changed_when: pull_result.rc != 0

    - name: Bring up containers
      ansible.builtin.command:
        cmd: docker compose -f /home/ubuntu/docker-compose.yml up -d
      args:
        chdir: /home/ubuntu
      register: up_result
      changed_when: up_result.rc != 0
